### ISSUE TITLE
Failed to get content

### ISSUE THREAD

**Issue by mangapolska** [cheelim1/image-updater#1]
```
Failed to get content: GET https://api.github.com/repos/company/repo1/contents/kubernetes/app.yaml: 404 Not Found []
```

**Comment by cheelim1** [comment]
can i see your example github action workflow step?
An example you want to update the `imageTag` in the github repo file in
`orgname/reponame/example/abc.yaml`

Example
```
      - name: Update Image Tag
        uses: cheelim1/image-updater@v1.11
        with:
          GITHUB_TOKEN: 'github_PAT_token'
          REPO_OWNER: 'orgname'
          REPO_NAME: 'reponame'
          FILE_PATH: 'example/abc.yaml'
          IMAGE_TAG: 'abcdef'
```

Ensure your github token has repo permission example:
<img width="589" alt="Screenshot 2023-11-08 at 5 23 43 PM" src="https://github.com/cheelim1/image-updater/assets/98261283/8075805d-4d81-4670-bb56-7e88f9541e2e">

If you organisation requires MFA ensure it's verified.

**Comment by mangapolska** [comment]
```
update:

    runs-on: ubuntu-latest

    steps:
    - name: Update Docker image for Kubernetes
      uses: cheelim1/image-updater@v1.11
      with:
        GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
        REPO_NAME: 'repo1'
        REPO_OWNER: 'company'
        FILE_PATH: 'kubernetes/app.yaml'
        IMAGE_TAG: 'amd64-${{github.sha}}'
        GITHUB_BRANCH: 'kube'
```
